remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Project Name Team 2
description: Github Pages site for the Team 2 Semester Project
show_downloads: true
google_analytics:
