remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Project Name Team 2
description: <div class="button-group">
    <a href="#" class="button primary">Dashboard</a>
    <a href="#" class="button">Inbox</a>
    <a href="#" class="button">Account</a>
    <a href="#" class="button">Logout</a>
</div>
show_downloads: true
google_analytics:
